//! Integration tests for loading image fixtures in every supported format and
//! for verifying the output-file counter logic when multiple source images share
//! the same stem.
//!
//! Fixture files live in `tests/fixtures/` and are generated by running
//! `bash tests/fixtures/gen.sh` (requires GraphicsMagick).  They are stored in
//! Git LFS and must be present locally before these tests can pass.

mod common;

use image::GenericImageView;
use sesoko::crop::YOLOCropper;
use sesoko::image_utils::open_image;

// ---------------------------------------------------------------------------
// Format lists
// ---------------------------------------------------------------------------

/// Formats that the `image` 0.25 crate can decode.
/// Each entry maps to `tests/fixtures/fixture.{ext}`.
/// Remove an entry to temporarily skip it; add one back to re-enable.
const DECODABLE_FORMATS: &[&str] = &["bmp", "gif", "jpg", "png", "tiff", "webp"];

// Formats not yet decoded by the `image` crate out of the box.
// Fixtures exist on disk; uncomment individual entries to add tests once the
// matching feature/crate is enabled (e.g. `image` feature "jxl", "avif",
// or `libheif-rs`):
//
// const NOT_YET_DECODABLE: &[&str] = &[
//     "avif",   // fixture generated on systems with gm AVIF delegate
//     "heic",   // fixture generated on systems with gm HEIC delegate
//     "jxl",    // enable with image feature "jxl" / jxl-oxide
// ];

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

/// Load every decodable fixture and assert it is a valid, non-empty RGB image.
#[test]
fn open_image_loads_all_decodable_fixtures() {
    let dir = common::fixtures_dir();
    for ext in DECODABLE_FORMATS {
        let path = dir.join(format!("fixture.{ext}"));
        let img = open_image(&path).unwrap_or_else(|e| panic!("failed to open fixture.{ext}: {e}"));
        let (w, h) = img.dimensions();
        assert!(w > 0 && h > 0, "fixture.{ext} has zero dimension");
        assert_eq!(
            img.color().channel_count(),
            3,
            "fixture.{ext} is not RGB (open_image should convert to RGB8)"
        );
    }
}

/// Copy all decodable fixtures into a temporary folder (all with the same stem
/// `fixture`) and run the cropper.  Because every output JPEG is written by
/// `unique_output_path`, the N inputs produce:
///
///   fixture.jpg, fixture_1.jpg, fixture_2.jpg, …, fixture_{N-1}.jpg
#[test]
fn process_folder_counter_on_same_stem() {
    use std::collections::BTreeSet;

    let fixtures = common::fixtures_dir();
    let input = tempfile::tempdir().unwrap();
    let output = tempfile::tempdir().unwrap();

    // Copy every decodable fixture into the temp input directory.
    for ext in DECODABLE_FORMATS {
        let src = fixtures.join(format!("fixture.{ext}"));
        let dst = input.path().join(format!("fixture.{ext}"));
        std::fs::copy(&src, &dst).unwrap_or_else(|e| panic!("failed to copy fixture.{ext}: {e}"));
    }

    let n = DECODABLE_FORMATS.len();
    let cropper = YOLOCropper::new(None, 64);
    let stats = cropper
        .process_folder(input.path(), output.path(), false)
        .expect("process_folder failed");

    assert_eq!(
        stats.processed.len(),
        n,
        "expected {n} processed, got {} processed / {} failed: {:?}",
        stats.processed.len(),
        stats.failed.len(),
        stats.failed,
    );

    // Collect the output filenames.
    let produced: BTreeSet<String> = std::fs::read_dir(output.path())
        .unwrap()
        .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
        .collect();

    // First input yields `fixture.jpg`; each subsequent one gets a counter suffix.
    let mut expected = BTreeSet::new();
    expected.insert("fixture.jpg".to_owned());
    for i in 1..n {
        expected.insert(format!("fixture_{i}.jpg"));
    }

    assert_eq!(produced, expected, "unexpected output filenames");
}
