use std::path::PathBuf;

/// Returns the root of the sesoko workspace/package.
/// Since this is now a single-crate project, CARGO_MANIFEST_DIR is the root.
pub fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Returns the directory containing test fixture images.
#[allow(dead_code)]
pub fn fixture_dir() -> PathBuf {
    workspace_root().join("tests")
}

/// Returns the directory containing format-specific fixture images
/// (generated by `tests/fixtures/gen.sh`).
#[allow(dead_code)]
pub fn fixtures_dir() -> PathBuf {
    workspace_root().join("tests").join("fixtures")
}
